export const categories = [
  'Accounting',
  'Acting',
  'Administrative Assistance',
  'Alternative Practices',
  'Animator & Entertainer',
  'Architect & Urbanist',
  'Art Related',
  'Auto-Mechanic',
  'Baker',
  'Bartending',
  'Beauty & Cosmetics',
  'Bicycle Mechanic',
  'Biology',
  'Blogger',
  'Brainstorming',
  'Business Consulting',
  'Business Counseling/Coaching',
  'Carpooling',
  'Chef',
  'Chemistry',
  'Child Care & Babysitting',
  'Cleaning & Laundry',
  'Climbing & Hiking',
  'Closet & Box Organizer',
  'Clothes & Wardrobe',
  'Collector',
  'Communication',
  'Company & Senior Care',
  'Computer Science',
  'Computer Support',
  'Craft Artist',
  'Cryptocurrency & Blockchain',
  'Dance',
  'Data Entry',
  'Data Scientist',
  'Delivery Services',
  'Design (Miscellaneous)',
  'Dog Walking',
  'Drawing/Sketching',
  'Driver',
  'Driving Instructor',
  'Economics',
  'Editor/Proofreader',
  'Electrician',
  'Engineering',
  'Farming & Agricolture',
  'Film Production',
  'Film/Video Maker',
  'Financial Specialist',
  'Fundraising',
  'Furniture Assembly',
  'Gardening & Landscaping',
  'General Tutoring',
  'Graphic Designer',
  'Green Economy & Technology',
  'Handyman',
  'Hardware Technician',
  'Health Educator/Coach',
  'Healthcare Practitioner',
  'History',
  'Home cook',
  'Hospitality/Innkeeping',
  'House Painting',
  'Humanities & Social/Applied Sciences',
  'Illustrator',
  'Insurance Specialist',
  'Interior Designer',
  'Journalist',
  'Languages & Translations',
  'Law',
  'Legal Support',
  'Life Coaching',
  'Literature',
  'Marketing & Sales',
  'Massage Therapy',
  'Math',
  'Medicine',
  'Meditation',
  'Mobility',
  'Model',
  'Mover',
  'Multimedia Artist',
  'Music Related Services',
  'Musician',
  'Nonprofit Consultant',
  'Organic Gardens',
  'Outdoor',
  'Painter & Sculptor',
  'Party & Events',
  'Personal Trainer',
  'Pet Sitter/Trainer',
  'Philosophy',
  'Photo/Video Editor',
  'Photographer',
  'Physicist',
  'Plumber',
  'Politics',
  'Programmer',
  'Psychologist',
  'Public Relations',
  'Publishing',
  'Reader',
  'Real Estate',
  'Recycling',
  'Repair & Restoration',
  'Restauration & Catering',
  'Resume/CV Writer ',
  'SEO/SEM Expert',
  'Science',
  'Security Guard/Bouncer',
  'Security Specialist',
  'Sharing Economy Expert',
  'Sharing Interests',
  'Shopping & Gift Helper',
  'Simple Tasks',
  'Singer',
  'Social Media Expert',
  'Social Worker',
  'Sociologist',
  'Spiritual Advisor',
  'Sport Coach/Enthusiastic',
  'Startup Advisor',
  'Statistician',
  'Stylist & Fashion Desig…',
  'System Engineer/Manager',
  'Tablet & Smartphone Guru',
  'Theology/Religion',
  'Therapy Assistance',
  'Tour Guide & Lifestyle',
  'Tradesperson',
  'Troubleshooter',
  'Usability & UI/UX',
  'Videogame Guru',
  'Volunteer',
  'Waiter',
  'Web Design',
  'Web Developer',
  'Web Research & Analysis…',
  'Webmaster/Web Project Manager',
  'Wi-Fi Sharing',
  'Wine & Beer Enthusiast',
  'Workspace/Meeting Space Provider',
  'Writer',
  'Yoga',
];
